---
- name: Hello World Sample
  hosts: all
  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    
    - name: test win_shell
      win_shell: write-host (get-date)
      register: cmd_result 
      
    - name: Create Temp folder
      win_file:
        path: 'C:\Temp2'
        state: directory
        
    - debug: msg="{{ cmd_result.stdout }}"
      
